// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjSem_Sklep_Lib.Context;

namespace ProjSem_Sklep_Lib.Migrations
{
    [DbContext(typeof(ProjSemDbContext))]
    [Migration("20220617193424_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ProjSem_Sklep_Lib.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SumPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Date = "25/06/2022",
                            SumPrice = 25m
                        },
                        new
                        {
                            ID = 2,
                            Date = "25/07/2022",
                            SumPrice = 25m
                        },
                        new
                        {
                            ID = 3,
                            Date = "25/08/2022",
                            SumPrice = 25m
                        });
                });

            modelBuilder.Entity("ProjSem_Sklep_Lib.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "tt",
                            Price = 2.65m,
                            Quantity = 1
                        },
                        new
                        {
                            ID = 2,
                            Name = "rr",
                            Price = 2.65m,
                            Quantity = 1
                        },
                        new
                        {
                            ID = 3,
                            Name = "yy",
                            Price = 2.65m,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("ProjSem_Sklep_Lib.Models.ProductOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductOrders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            OrderId = 1,
                            ProductId = 2
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = 1
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = 2
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = 3
                        });
                });

            modelBuilder.Entity("ProjSem_Sklep_Lib.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IsAdmin = true,
                            Login = "admin",
                            Password = "admin"
                        },
                        new
                        {
                            ID = 2,
                            IsAdmin = true,
                            Login = "user",
                            Password = "user"
                        });
                });

            modelBuilder.Entity("ProjSem_Sklep_Lib.Models.ProductOrder", b =>
                {
                    b.HasOne("ProjSem_Sklep_Lib.Models.Order", "Order")
                        .WithMany("ProductOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjSem_Sklep_Lib.Models.Product", "Product")
                        .WithMany("ProductOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProjSem_Sklep_Lib.Models.Order", b =>
                {
                    b.Navigation("ProductOrders");
                });

            modelBuilder.Entity("ProjSem_Sklep_Lib.Models.Product", b =>
                {
                    b.Navigation("ProductOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
